### ISSUE TITLE
Owner field?

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#10]
On web ui the 'Owner' field is prominently visible. Is that the material owner and would there be a field in API to enable setting that field up?

As an additional request, the first letter of the owner field should be capitalized.

**Comment by Tumetsu** [comment]
Owner field is the name of the organization which is defined when the credentials to the system are given to the organization. So it is the material provider (CMS).

First letter is now capitalized.
