### ISSUE TITLE
500 error if scandinavian chars in tags?

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#11]
Stumbled to one of our materials, which causes 500 error from the API. All similar data goes through, but this one did not. Only after removed the tags with scandinavia chars, then it went through?

'tags' => [   "keksinn\x{f6}t",  'kuumailmapallot',   "lent\x{e4}minen", 'Pariisi'],
'contributionDate' => '1871-01-04',

**Comment by Tumetsu** [comment]
Tags support now scandinavian characters.
