### ISSUE TITLE
API workings?

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#12]
Has something changed from yesterday in API? Data sent yesterday, is not approved today.  For example cannot send updates to the data sent yesterday, getting just the "Error: Missing or invalid json-field. Update failed."

Tried adding "visible":true, which looked like a new one, but getting: 
"Error: Incorrect format in boolean field. Should be either 'true' or 'false'"
E.g.  0, 1 as false , true, would be nice, as then more states for drafts etc. could be added (like in the APIv1).

**Comment by DeWa** [comment]
Yes, it has changed. We really have added a visible-field, which can be used to determine the product visibility in the shop. From now on, we try to keep  [Api Definition](https://github.com/koulutuksenpilvivayla/pilvivayla-basaari/wiki/API-Definition) updated on every update.  
Your format was almost correct. The system uses the true and false values​​, but they need to put between ""-characters, like "visible": "true". 
0 and 1 is a good idea. We'll keep that in mind.

**Comment by TuulaP** [comment]
Tried with this : "visible":"true" , but then getting "Error: Missing or invalid json-field. Update failed." (wouldn't "" mark it as string, and then it wouldn't go through because of that?

(tried also with 'true' etc. but no combo that I tried helps)

Here is the whole json of what I try to insert: https://drive.google.com/file/d/0BwMuTNoamhKdM1dfOHUwSXRfMWc/edit?usp=sharing

**Comment by DeWa** [comment]
Hi,
The error messages is caused by the subject field. In the newest version a product can has multiple subjects, so we changed subject field into array named subjects (example "subjects": ["Math"]

Price should also be without quotation marks, e.g. "price": 12.0

Here should be working json
https://drive.google.com/file/d/0B472h2dz_JfaYS1relJ5b2xRZjQ/edit?usp=sharing
