### ISSUE TITLE
Bit more tags, please?

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#13]
Currently CMS-Basaar API accepts 0-5 tags for each material type. 
https://github.com/koulutuksenpilvivayla/pilvivayla-basaari/wiki/API-Definition 

In some rare cases it seems that there would be need to have bit more. Would it be possible to increase amount of tags to 7 or 10? We can live with current amount, but have to just drop some tags in some cases, so if impossible just reject this one. :coffee:

**Comment by kyyberi** [comment]
I vote for 10, unless there is some technical or UI/UX related reason not to.

**Comment by Tumetsu** [comment]
Ten tags it is f3815a8db35695123d842fe89eba438af865a9a1
Will be soon on the demo server when we do the next update there.
