### ISSUE TITLE
Kansalliskirjaston materiaalista - kuinka raakaa / tuotteistettua

### ISSUE THREAD

**Issue by kyyberi** [educloudalliance/educloud-bazaar-legacy#14]
Hei

Huomasin että kansalliskirjastosta on ansiokkaasti laitettu materiaalia rajapinnan kautta EduCloud basaariin. Ehkä haluaisin vain nostaa esiin sen että kuinka raakaa materiaalia on mielekästä viedä Basaariin. 

Nyt käytännössä sinne on laitettu muun muassa joku yksittäinen vanha mainos jostain lehdestä. Tämä tie johtaa siihen että replikoimme kansalliskirjaston metatiedot Basaariin. Se ei varmaan ole mielekästä kenenkään näkökulmasta. 

Sen sijaan kansalliskirjaston materiaali tulisi tuotteistaa ja ”niputtaa” mielekkäiksi kokonaisuuksiksi ja ne sitten tuotaisiin basaariin. Yksittäisiin materiaaleihin pääsee jo nyt hyvin käsiksi Kansalliskirjaston käyttöliittymän kautta. Sama kysymys koskee tietysti geneerisesti kaikkia materiaalintuottajia. 

Mitä ajatuksia tämä herättää…

**Comment by johannespernaa** [comment]
Luin juuri Työmiestä 16.03.1900. Käsittämättömän hienoa.

Pohdintaani: Kansalliskirjasto on digitoinut vanhoja aikakauslehtiä, ja hyödyntää EduCloudia (EC) niiden jakamiseen. EC tarjoaa hakukoneen, ostoprosessin yhteydessä materiaalin linkki jää käyttäjän profiilin ja hän voi sen kautta palata helposti aineistoihin.

Jos itselleni tulisi henk.koht tarve käyttää Kansalliskirjaston aikakauslehtiarkistoa niin käyttäisin nimekkeiden tallentamiseen ja järjestämiseen ehkä mielummin Zoteroa, joka on web-pohjainen viitehallintatyökalu. Se on parempi kirjastotyökalu kuin EC:n ostokuitti. Hakisin lehdet suoraan Kansalliskirjaston omasta palvelusta, enkä käyttäisi EC:tä missään vaiheessa.

Jos käyttäisin sitä opettajana osana oppituntia niin tarvitsisin EC:stä kustomoidumman haun, eli kemian opettajana voisin tarvita esimerkiksi uutisia kotimaisista aikakauslehdistä vaikkapa kemian teollisuudesta. Hakusanalla "kemian teollisuus" saisin yhden aineistopaketin / -linkin, jonka voisin heittää käyttämäni oppimisalustan ongelmanratkaisutehtävänannon-kohtaan virittäytymisaineistoksi.

Tästä linkistä menijä saisi käsiinsä nipun kemian teollisuutta käsitteleviä artikkeleita useista lehdistä eri vuosilta.

Minulla ei ole tietoa saako näin tarkkoja hakuja tehtyä, mutta tämä olisi yksi aito opettajan tarve.

Voiko asiaa peilata muihin palvelun tarjoajiin? Olen ajatellun, että joskun kun e-Opin teokset voi hankkia EC:n kautta, niin hakasanalla "Kemia" tulee iso kasa eri kustantajien kemian oppikirjoja yms kemian materiaalia.

Hakufraasilla "Kemia 1: Ihminen ja elinympäristö" tulee eri kustantajien sarjojen kemia 1-teokset.

Tämä on mielestäni riittävä tarkkuus, mutta oppikirjat ovatkin jo melko viimeisteltyjä paketteja, joilla on selkeä käyttötarkoitus.

**Comment by TuulaP** [comment]
Juuri tällaisia tietopaketteja on tarkoitus loppujen lopuksi tuottaa Basaariin. Nyt kun tuota CMS-APIa on kehitetty, tuli protoiltua ja testailtua miten erilaiset aineistot voisivat toimia basaarissa. Backlogillani on ensi viikolla alkaa laittaa ns. "kokonaisuuksia" eli  asiasana-pohjaisia hakuja sisällöksi, esim. http://digi.kansalliskirjasto.fi/sanomalehti/articles#?keywords=siirtolaisuus , silloin tieto tulee hallittavammin esille ja tuottavat enemmän lisäarvoa. 

Toisaalta, visioin mielessäni käyttötapausta, jossa opettaja on ensin hankkinut sähköisiä opetuspaketteja Basaarista, niin oston lopuksi voisi napata leikkeen tai pari kylkiäisiksi aineiston rikasteeksi. Niillä voisi sitten aktivoida oppijaa etsimään aiheesta lisää muualtakin. Tämä idea toimii joka tapauksessa sekä tietopakettien & yksittäisten leikkeiden kanssa.

Muuten, jos joku on opettajien kanssa puheissa, niin saa välittää tietoa mitä erityisesti kaivattaisiin, voisin nostella niitä erityisesti Basaarin puolelle.
