### ISSUE TITLE
Search does not work with 'Ä'

### ISSUE THREAD

**Issue by preriasusi** [educloudalliance/educloud-bazaar-legacy#18]
1. Go to demo.pilvivayla.fi
2. Search 'hetys" -> one result found 'Testilähetys'
3. Search 'ähetys' -> no results

**Comment by preriasusi** [comment]
No, it's not about 'ä'. When you take some part of the word, it's bit random when it finds, and when it doesn't.

**Comment by preriasusi** [comment]
Fixed by Ville.

**Comment by jykae** [comment]
Solr config was not using Oscar specific stuff. Now it's linked at demo.pilvivayla.fi
