### ISSUE TITLE
Mepin login forwards to demo.pilvivayla.fi, when I run Basaar in localhost

### ISSUE THREAD

**Issue by preriasusi** [educloudalliance/educloud-bazaar-legacy#19]
1. Install basaar local dev environment: https://github.com/koulutuksenpilvivayla/pilvivayla-provisioning
2. Run basaar in localhost.
3. Log in with me pin
4. After login, you are not in localhost anymore, you are in demo.pilvivayla.fi

**Comment by dveerendra** [comment]
Yes, mepin doesnot work with localhost. If you try to login through localhost it will redirect to demo server because call back url settings is written to redirect to demo server.

So, if you wanna test 'mepin' we should only test from demo.pilvivayla.fi.
