### ISSUE TITLE
Search does not work with some strings

### ISSUE THREAD

**Issue by dveerendra** [educloudalliance/educloud-bazaar-legacy#20]
when we search with testi. we can see three items. But there is a item with name:  testi4

if I search with 'testi4' it shows 'No results found'

**Comment by jykae** [comment]
This is because it only searches from description by default. Tuomas is learning and working on this.

**Comment by dveerendra** [comment]
ok :)

**Comment by jykae** [comment]
Not solved :)

**Comment by dveerendra** [comment]
Thanks for reopening. Yes i checked again with some words in description. It didnot work

**Comment by Tumetsu** [comment]
The search needs indexing update after new product additions. Now the server should update the new indexes hourly.

**Comment by jykae** [comment]
sounds rational :+1: Let's see if that fixes it. Could you @dveerendra verify? :)

**Comment by dveerendra** [comment]
It works fine with product name. Cool :+1:
