### ISSUE TITLE
Problem loading jQuery files over HTTPS

### ISSUE THREAD

**Issue by jykae** [educloudalliance/educloud-bazaar-legacy#21]
I get the following errors from Chromium console on Ubuntu 14.04:

The page at 'https://demo.pilvivayla.fi/fi/suomenkieliset-tieto-sanomat_9/' was loaded over HTTPS, but displayed insecure content from 'http://api.longurl.org/v2/expand?callback=jQuery19103322337542194873_140844…00%3Flist%3DPLwgL7HJKiz4wQytOQTc3bJbtw_JtDhIkd&format=json&_=1408445152623': this content should also be loaded over HTTPS.
 (index):1
Failed to load resource: the server responded with a status of 400 (Bad Request) http://api.longurl.org/v2/expand?callback=jQuery19103322337542194873_140844…00%3Flist%3DPLwgL7HJKiz4wQytOQTc3bJbtw_JtDhIkd&format=json&_=1408445152623
XMLHttpRequest cannot load http://api.longurl.org/v2/expand?callback=jQuery19103322337542194873_140844…00%3Flist%3DPLwgL7HJKiz4wQytOQTc3bJbtw_JtDhIkd&format=json&_=1408445152623. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://demo.pilvivayla.fi' is therefore not allowed access. (index):1

**Comment by machadolucas** [comment]
I tried to load the link observing the console but I could’t reproduce the issue. There are no errors.
Can you check if the problem still persists?

**Comment by jykae** [comment]
no problem anymore :) works checked on Firefox and Chromium on Ubuntu.
