### ISSUE TITLE
Simplified material inserting form status?

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#26]
At some point there was discussion that there might be some "simplified material inserting form", i.e. some form by which any authorized user, could add material to Basaar?  Is there anything going to happen to with it by end of October (or this year)?

There seems to be some needs for it, so thinking whether to just implement sth like that on our side. 
As an light-weight UI with couple of user-editable fields for the other kinds of users.

**Comment by kyyberi** [comment]
As far as I know, that is on the backlog. At the moment SSO authentication is number one and only item under work. That looks promising so, possibly we might doing the UX for material management. If I'm not wrong, we had a draft about the UX at consortium meeting...

**Comment by TuulaP** [comment]
Yes, saw UX, looked good. Now only question is when? ;)

**Comment by kyyberi** [comment]
Beats me :) Vesa still manages backlog :) ping @preriasusi

**Comment by preriasusi** [comment]
Educloud autumn team started on Monday, and one of the items we started to work with is control panel, that is exactly what TuulaP was asking. Control panel was already started by summer team, and we will now finish it. 

Tomorrow we'll think with @jykae what would be the best place to share what we are working for, and our backlog. Any suggestions?

**Comment by kyyberi** [comment]
Trello

**Comment by preriasusi** [comment]
https://trello.com/b/Hd0KAg0g/educloud-autummn

There it is. I was thinking more to have a blog, but now I think both is better. Adding todo -tasks still todo.

**Comment by jykae** [comment]
Assuming that panel was implemented by @DeWaster ? Is this done?

**Comment by DeWa** [comment]
It's done https://github.com/educloudalliance/educloud-bazaar/tree/master/bazaar/apps/panel
