### ISSUE TITLE
Ages vs. grades

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#27]
Hi, It seems that minimumAge of the API converts directly to the corresponding grade range?
E.g. MinAge: 1, MaxAge: 9 and grade shows as 1-9.

Then second question from LMS workings, if CMS marks certain material to grade: 9, can LMS side then "override" it, if teacher so chooses? I.e. would LMS block certain age range in some cases?

**Comment by preriasusi** [comment]
ping @DeWaster

**Comment by DeWa** [comment]
The conversion to the grades is actually done only in the front-end part of the system, so it's not saved anywhere. Metadata is still in the database as e.g. MinAge: 1, MaxAge: 99 and LMS gets it in that format.
And about the conversion: Basaar converts ages 0-7 to the grade 1, age 8 to the grade 2 etc.
