### ISSUE TITLE
Domain changes ahead

### ISSUE THREAD

**Issue by kyyberi** [educloudalliance/educloud-bazaar-legacy#32]
For all to know that there will be domain changes in the near future. This affects all our services whichj have any kind of pilvivayla.fi domain name. 

We will move to educloudalliance.org domain. 
- Pilviväylä -> educloudalliance.org
- Bazaar (name is now fixed to that) -> bazaar.educloudalliance.org
- Kysy -> ask.educloudalliance.org and kysy.educloudalliance.org

The transition will happen as soon as COSS informs the capability to do DNS changes. Team (Vesa or Ville) will coordinate this change. In the future COSS manages all DNS records and we will no longer use funet DNS services. Contact Timo Väliharju from COSS to discuss details.

**Comment by jykae** [comment]
Changing or getting new wild card SSL certificate, that is currently *.pilvivayla.fi is the another important thing with these domain changes.

**Comment by kyyberi** [comment]
Good point!

**Comment by jykae** [comment]
Domain changes done. Closing issue.
