### ISSUE TITLE
Get Inspired => Inspiroidu!

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#38]
Get inspired is better term, but now with otherwise Finnish UI that is bit inconsistent - could it be translated to e.g. 'Inspiroidu!' to show it as it is.

**Comment by jykae** [comment]
How about "Innostu!" as more finnish word?

**Comment by TuulaP** [comment]
Vielä parempi :)

**Comment by DeWa** [comment]
Changed into "Innostu!" commit 2614a6b9eb7910082578c021df3ca092a31560af
