### ISSUE TITLE
Give hint of which field was missing/invalid in POSTs 

### ISSUE THREAD

**Issue by TuulaP** [educloudalliance/educloud-bazaar-legacy#4]
Using of the API would be more easier , if the error message of the response would be more verbose. Currently response says: "Error: Missing or invalid json-field. Update failed."

System probably knows **which field** failed, so please return that information. (If there are multiple fields, either return them all or just first one. Both solutions would enable better ways to fix things.)

**Comment by Tumetsu** [comment]
We forgot to mention in the mail that in previous sprint we didn't have to time to focus on error handling and that the current messages will be formalized in incoming sprints and will include more data of the error.
