### ISSUE TITLE
OID not found and SSO login fails

### ISSUE THREAD

**Issue by jplahti** [educloudalliance/educloud-bazaar-legacy#50]
New Peda.net users created in to role-db get ""Error: No user with this oid in the database." when using the LMS-API for Bazaar. This might be related to the situation, when the new users have not yet logged in to Bazaar and have no "purchased items" available.

Logging in directly to Bazaar might fix this, but for some reason direct login using EduCloud SSO with Peda.net-JWT-authentication fails.

Linking Peda.net account to EduCloud OID works with the flow:
Peda.net -> EC SSO -> Peda.net-JWT -> EC SSO -> Peda.net

But login flow from Bazaar:
Bazaar -> EC SSO -> Peda.net-JWT -> EC SSO -> Bazaar

fails on returning to Bazaar.

Test account which fails on this can be get from juha.lahti@peda.net.

**Comment by jykae** [comment]
The mysterious test account worked today flawlessly. @jplahti continues investigations..

**Comment by jplahti** [comment]
Seems that this was just a temporary server error. Waiting for other users with new accounts to verify that this is working now before closing this bug.

**Comment by jplahti** [comment]
Verified to be working. So this was only a temporary server error.
