### ISSUE TITLE
Text notice that only EduCloud Pilot users can use EduCloud SSO login.

### ISSUE THREAD

**Issue by jykae** [educloudalliance/educloud-bazaar-legacy#54]
Notice to Bazaar and EduCloud SSO.

Related:
https://github.com/educloudalliance/educloud-bazaar/issues/52

**Comment by jykae** [comment]
WIP at development server: Modified Login look&feel in Bazaar. Adding text under login tomorrow to both Bazaar and EC SSO.

**Comment by jykae** [comment]
MePIN login widget removed.

**Comment by jykae** [comment]
Decided with @preriasusi that you could fix these Bazaar side bugs.

**Comment by preriasusi** [comment]
Message is there.
